added detailed tables for feature importance when CV
AstraZeneca-NGS/LogMl pull request #92
Opened 2020-11-16 09:28 UTC by maxmykhailenko

Each model have each detailed table on page.

Example of detailed tables for ****NO** cross validation and **ONE** iteration**
<img width="990" alt="Screenshot 2020-11-16 at 11 20 14 AM" src="https://user-images.githubusercontent.com/66369398/99235285-566b9680-27fe-11eb-84b1-668703d6f47d.png">

Example of detailed tables for ****NO** cross validation and **MULTIPLE** iteration**
<img width="1016" alt="Screenshot 2020-11-16 at 11 21 29 AM" src="https://user-images.githubusercontent.com/66369398/99235345-68e5d000-27fe-11eb-931b-473d5f122c18.png">

Example of detailed tables for ****MULTIPLE** cross validation and ** MULTIPLE** iteration**
<img width="1449" alt="Screenshot 2020-11-16 at 11 22 45 AM" src="https://user-images.githubusercontent.com/66369398/99235397-7602bf00-27fe-11eb-9e38-22eddec97078.png">

2020-11-26 13:44 UTC, pcingola requested changes

2020-11-26 13:44 UTC, pcingola commented on src/tests_integration.py
> +
This is great, thank you for adding the test with scatter gather.

What we'd like to do is to extend this code to run ALL integration tests twice: 1) without scatter/gather, and 2) with scatter/gather.

I think it could be achieved by refactoring the code that runs `ml()` into a function that runs with/without scatter gather.....

```
def run_logml(config_file, use_scatter_gather): 
   ....

def run_test_linear3(self, use_scatter_gather):
    ... # code for preparing the test
    run_logml(config_file, use_scatter_gather)
    ... # code to check results

# Then for each test we do these two functions (with and without scatter/gather)
def test_linear3(self):
  self.run_test_linear3(False)

def test_linear3_with_scatter_and_gather(self):
  self.run_test_linear3(True)

2020-11-26 13:44 UTC, pcingola commented on src/logml/feature_importance/feature_importance_model.py
> +            results = np.array(self.performance[col_name][0]).ravel()
Please add a comment on why you need the `[0]` here, it's not obvious from the code..

2020-12-01 12:25 UTC, maxmykhailenko commented on src/tests_integration.py
> +
nice comment. Done

2020-12-01 12:25 UTC, maxmykhailenko commented on src/logml/feature_importance/feature_importance_model.py
> +            results = np.array(self.performance[col_name][0]).ravel()
Done

2021-01-11 13:34 UTC, merged