WIP: communication interface class
AstraZeneca-NGS/LogMl pull request #99
Opened 2021-02-05 21:26 UTC by maxmykhailenko

I have some open question which would like to ask. After that I can add the class description.

2021-02-06 21:54 UTC, pcingola commented
I think we need a method for feature importances that optionally returns the importances from the model if they exist (or None if they don't).

2021-02-18 01:40 UTC, pcingola reviewed
Each method MUST be thoroughly documented.

2021-02-18 01:40 UTC, pcingola commented on communication_interface.py
> +
Typo `congig=config`

2021-02-18 01:40 UTC, pcingola commented on communication_interface.py
> +        """ Save dataset to pickle file """
Why do you need `data` to save? Isn't this supposed to save the Model object (i.e. `self`)?

2021-02-18 01:40 UTC, pcingola commented on communication_interface.py
> +        """ Save dataset to pickle file """
What is `tag` for? Why are you forcing all models to pass this parameter to save the model?

2021-02-18 01:40 UTC, pcingola commented on communication_interface.py
> +        """Load a pickle file, return data (on success) or None (on failure)"""
Why do you need `tag` here and why is it a mandatory parameter?

2021-02-18 01:40 UTC, pcingola commented on communication_interface.py
> +            if not file_pickle:
If you only require the `config` file when `file_pickle` is no passed, shouldn't `file_pickle` and `config` have default None values?

2021-02-18 01:56 UTC, pcingola requested changes

2021-02-18 01:56 UTC, pcingola commented on communication_interface.py
> +            return False
What is `logger`? Where is this coming from?

2021-02-18 01:56 UTC, pcingola commented on communication_interface.py
> +            return self.model.feature_importances_
Where is `self.cv_enable` defined?
Where are these `self.model` and `self.model.feature_importances_` comming from?

2022-04-14 09:48 UTC, nchaly commented
Closing this as outdated request.

2022-04-14 09:48 UTC, closed without merging